-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Grocery CASCADE;
DROP TABLE IF EXISTS Customer CASCADE
DROP TABLE IF EXISTS vendor CASCADE; 
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS kayttaja CASCADE;
DROP TABLE IF EXISTS vendor CASCADE;
DROP TABLE IF EXISTS Product CASCADE; 
DROP TABLE IF EXISTS Reviews CASCADE; 
-- DROP TABLE IF EXISTS aanestys CASCADE; 